/* Portfolio data — shared across the site. Edit projects here. */
window.PORTFOLIO_DATA = {
  projects: [
    { name: 'Nesto UZ',        url: 'https://github.com/asadbekabdulboqiyev/nesto-uz',            desc: "O'zbekistondagi ish va uy-joy bozori ilovasi. AI bilan kuchaytirilgan — real estate va job marketplace bir platformada.",            tags: ['Flutter','AI','Dart','Marketplace'], geo: 'cube' },
    { name: 'Hisob',           url: 'https://github.com/asadbekabdulboqiyev/hisob',               desc: "Shaxsiy moliya va byudjet nazorati ilovasi. Flutter + FastAPI backend bilan — xarajatlarni kuzatib boring, o'zgartiring.",                 tags: ['Flutter','FastAPI','Dart','Finance'],  geo: 'octa' },
    { name: 'Bloom & Petal',   url: 'https://github.com/asadbekabdulboqiyev/florist-app',         desc: "Premium florist e-commerce app. Firebase backend, beautiful UI, real-time order tracking va delivery system bilan to'liq shop.",    tags: ['Flutter','Firebase','E-Commerce','Dart'], geo: 'ring' },
    { name: 'Zer Language IDE',url: 'https://github.com/asadbekabdulboqiyev/zer-language-ide',    desc: "Zer dasturlash tili uchun Flutter-based IDE. Syntax highlighting, code editing va real-time execution — hammasi mobile'da.",       tags: ['Flutter','IDE','Dart','Dev Tool'],      geo: 'tetra' },
    { name: 'Tinchlik',        url: 'https://github.com/asadbekabdulboqiyev/tinchlik',            desc: "Meditation and mindfulness app. Ongni tinchlantiruvchi ilova — guided meditations, breathing exercises, va daily tracker.",      tags: ['Flutter','Wellness','Dart','UI/UX'],    geo: 'sphere' },
    { name: 'Mini Metro Runner',url: 'https://github.com/asadbekabdulboqiyev/mini-metro-runner',  desc: "Endless runner game built with Flutter va Flame engine. Tezlik, to'siqlar, va high score — o'ynash oson, yutish qiyin.",        tags: ['Flutter','Flame','Game','Dart'],        geo: 'dode' },
    { name: 'Weather App',     url: 'https://github.com/asadbekabdulboqiyev/weather-app',         desc: "Beautiful Flutter weather application. Real-time weather data, forecasts, va chiroyli animations bilan ob-havo ilovasi.",       tags: ['Flutter','API','Dart','Weather'],       geo: 'ico' },
    { name: 'NexPay Business', url: 'https://github.com/asadbekabdulboqiyev/nexpay-business',     desc: "Business payment va invoicing app. To'lov tizimi, invoice yaratish, va moliyaviy hisobotlar — hammasi bir joyda.",              tags: ['Flutter','Fintech','Dart','Payments'],  geo: 'coin' },
    { name: 'Social Hub',      url: 'https://github.com/asadbekabdulboqiyev/social-hub',          desc: "Flutter social networking application. Post sharing, real-time messaging, va community features — ijtimoiy tarmoq ilovasi.",      tags: ['Flutter','Social','Dart','Real-time'],  geo: 'knot' },
    { name: 'E-Commerce App',  url: 'https://github.com/asadbekabdulboqiyev/ecommerce',           desc: "Flutter e-commerce application. Product catalog, shopping cart, va checkout flow — to'liq onlayn do'kon tizimi.",                 tags: ['Flutter','E-Commerce','Dart','Cart'],   geo: 'store' },
    { name: 'FreshLink',       url: 'https://github.com/asadbekabdulboqiyev/freshlink',           desc: "Connect with fresh produce and local farmers markets. Mahalliy fermerlar bilan bog'lanish, yangi mahsulotlar topish.",             tags: ['Flutter','Marketplace','Dart','Local'],  geo: 'capsule' },
    { name: 'Day0 Bot',        url: 'https://github.com/asadbekabdulboqiyev/telegram-ai-bot',     desc: "AI Telegram bot powered by Groq Llama. Savol-javob, matn generatsiyasi va AI bilan suhbat — Telegram'da.",                        tags: ['Python','AI','Telegram','Groq'],        geo: 'cone' }
  ],
  matColors: [0x97c459, 0xb9d97a, 0x7daf4e, 0xd3f0b0, 0x639922, 0xa5cd6b, 0x8fbd5c, 0xc4e68a, 0x6f9e3f, 0xaae07a, 0x82b254, 0xbdd88f]
};
